services:
  app:
    build: .
    container_name: eco-quest-2026
    restart: always
    ports:
      - "3001:3001"
    environment:
      - TOKEN_TUNNEL=${TOKEN_TUNNEL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AUTH_TRUST_HOST=true
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    command: tunnel run --token ${TOKEN_TUNNEL}
    restart: unless-stopped
    depends_on:
      - app